window.CHIRODESK_CONFIG = {
  SUPABASE_URL: 'https://pxubjqdwsrttwcrsuuwg.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dWJqcWR3c3J0dHdjcnN1dXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0MTAxODcsImV4cCI6MjA5NDk4NjE4N30.XOGfpy0ihvsNVdAq0Y9VcDFWTxbcEaEyQ5Mxe2MFf7M
',
  NOTIFY_WEBHOOK_URL: ''
}
