export const SPECIALTIES = {
  chiro: {
    label: 'Chiropractor',
    icon: '🦴',
    noteType: 'SOAP',
    cptCodes: ['98940','98941','98942','97012','97110','97530','97035','97014'],
    icd10Prefix: ['M54','M47','M99','S13','M50','M51'],
    showSubgraph: true,
    showTechniques: true,
    medicareAT: true,
  },
  pt: {
    label: 'Physical Therapist',
    icon: '🏃',
    noteType: 'SOAP',
    cptCodes: ['97110','97530','97140','97150','97012','97530'],
    showSubgraph: false,
    showTechniques: false,
    medicareAT: false,
  },
  massage: {
    label: 'Massage Therapist',
    icon: '💆',
    noteType: 'Session',
    cptCodes: [],
    showSubgraph: false,
    showTechniques: false,
    medicareAT: false,
    intakeExtras: ['pressure_preference', 'contraindications', 'areas_to_avoid'],
  },
  mental: {
    label: 'Mental Health',
    icon: '🧠',
    noteType: 'DAP',
    cptCodes: ['90834','90837','90847','90853'],
    showSubgraph: false,
    showTechniques: false,
    medicareAT: false,
    showCrisisLine: true,
  },
  acupuncture: {
    label: 'Acupuncture',
    icon: '📍',
    noteType: 'TCM',
    cptCodes: ['97810','97811','97813','97814'],
    showSubgraph: false,
    showTechniques: false,
    medicareAT: false,
    intakeExtras: ['tongue_diagnosis', 'pulse_diagnosis', 'pattern'],
  },
}
